syntax = "proto3";

package akuity.types.events.v1;

option csharp_namespace = "Akuity.Types.Events.V1";

option go_package = "github.com/akuityio/akuity-platform/pkg/api/gen/types/events/v1;eventsv1";

option java_multiple_files = true;

option java_outer_classname = "EventsProto";

option java_package = "com.akuity.types.events.v1";

option objc_class_prefix = "ATE";

option php_metadata_namespace = "Akuity\\Types\\Events\\V1\\GPBMetadata";

option php_namespace = "Akuity\\Types\\Events\\V1";

option ruby_package = "Akuity::Types::Events::V1";

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;

  EVENT_TYPE_ADDED = 1;

  EVENT_TYPE_MODIFIED = 2;

  EVENT_TYPE_DELETED = 3;
}
